<!DOCTYPE html>
<html>
<head>
    <title>Реєстрація</title>
</head>
<body>
<h2>Реєстрація користувача</h2>
<form method="post" action="/register">
    <label>Ім’я користувача: <input type="text" name="username"/></label><br/>
    <label>Пароль: <input type="password" name="password"/></label><br/>
    <label>Роль: <input type="text" name="role"/></label><br/>
    <button type="submit">Зареєструватися</button>
</form>
</body>
</html>
